#!/bin/sh
### BEGIN INIT INFO
# Provides:          chromeboxcontroller
# Required-Start:    $avahi-daemon
# Should-Start:	     $syslog
# Required-Stop:     $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Chromebox Controller remote support
# Description:       Allows remote control from android application
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="Chromebox Controller"
NAME="ChromeController"
DAEMON="/usr/local/bin/$NAME"
SCRIPTNAME=/etc/init.d/chromeboxcontroller
PIDFILE=/var/run/$NAME.pid

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

. /lib/lsb/init-functions

# Include check if script directory exists
test -d /etc/$NAME/scripts

#
#       Function that starts the service.
#
d_start() {
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null || return 1
	start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON || return 2
}

#
#       Function that stops the daemon/service.
#
d_stop() {
	start-stop-daemon --stop --quiet --retry=HUP/10/KILL/5 --pidfile $PIDFILE --exec $DAEMON --oknodo
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2

	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
	[ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE
	return "$RETVAL"
}

#
#       Function that reload the config file for the daemon/service.
#
d_reload() {
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        d_start
        log_end_msg $?
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        d_stop
        log_end_msg $?
        ;;
    restart)
        log_daemon_msg "Restarting $DESC" "$NAME"
        d_stop
        if [ "$?" -eq 0 ]; then
                d_start
                log_end_msg $?
        else
                log_end_msg 1
        fi
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart}" >&2
        exit 3
        ;;
esac

exit 0
